# Generated by Django 6.1.1

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('usuarios', '0002_registroauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventario_fotos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='usuarios.sede')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productoinventario',
            index=models.Index(fields=['sede', 'categoria'], name='inventario_sede_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='productoinventario',
            index=models.Index(fields=['fecha_actualizacion'], name='inventario_fecha_idx'),
        ),
    ]
